# Travis CI
language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "10"

sudo: false

git:
  submodules: false

notifications:
  email:
    recipients:
      - SuriyaaKudoIsc@users.noreply.github.com
    on_success: change # default: change
    on_failure: always # default: always

before_script:
  - npm install

install:
  - gem install travis-lint
  # Install Jekyll and dependencies
  ## - bundle install

script:
#  - jekyll build
